export const firestoreCollections = {
  users: 'users',
  activationTokens: 'activationTokens',
  businessProfiles: 'businessProfiles',
  publicVendorProfiles: 'publicVendorProfiles',
  bankAccounts: 'bankAccounts',
  packageCategories: 'packageCategories',
  packages: 'packages',
  clients: 'clients',
  invoiceSequences: 'invoiceSequences',
  receiptSequences: 'receiptSequences',
  invoices: 'invoices',
  invoiceItems: 'invoiceItems',
  invoiceEvents: 'invoiceEvents',
  payments: 'payments',
  receipts: 'receipts',
  agreements: 'agreements',
  pricelists: 'pricelists',
  backupLogs: 'backupLogs',
  auditLogs: 'auditLogs',
} as const
